### ISSUE TITLE
Is this plugin production ready?

### ISSUE THREAD

**Issue by rameerez** [agence-gaya/traefik-plugin-cloudflare#1]
Hi! I'm interested in using this Traefik plugin in a few production sites. Just wondering, since the repo is only a week old, if you'd consider the plugin as production ready – has it been tested under real production traffic before and ensured it works fine?

Thanks for making this! Easiest + most complete Traefik plugin to set real Cloudflare IPs I've seen

**Comment by jliebert** [comment]
Hi, thanks for you interest,

Is it currently under production final acknowledgement, features are
stable, somes optimisations concerning debug and testing have to be
done.
We must also add some documentation on use cases, I will agree to
answer to you about if you need.
It is used without trouble on a production website at this moment,
more sites will use it shortly.
It will be maintained.

Regards,
