### ISSUE TITLE
"refreshInterval: 0" seems to be not working

### ISSUE THREAD

**Issue by alexander-zimmermann** [agence-gaya/traefik-plugin-cloudflare#2]
I set the refreshInterval to 0. 

```
http:
  middlewares:
    cloudflare:
      plugin:
        cloudflare:
          debug: true
          trustedCIDRs: '{{env "$CLOUDFLARE_IPv4,$CLOUDFLARE_IPv6"}}'
          allowedCIDRs: '{{env "$LOCAL_IPv4"}}'
          refreshInterval: 0
          overwriteRequestHeader: false
```

According to the log files, it still refresh cidrs (or the the log output is missleading).

```
time="2024-03-24T10:07:30+01:00" level=error msg="2024/03/24 10:07:30 info: refresh cidrs successfull" plugin=plugin-cloudflare module=github.com/agence-gaya/traefik-plugin-cloudflare
time="2024-03-24T10:07:30+01:00" level=error msg="2024/03/24 10:07:30 info: refresh cidrs successfull" plugin=plugin-cloudflare module=github.com/agence-gaya/traefik-plugin-cloudflare
time="2024-03-24T10:07:30+01:00" level=error msg="2024/03/24 10:07:30 info: refresh cidrs successfull" plugin=plugin-cloudflare module=github.com/agence-gaya/traefik-plugin-cloudflare
```

BTW: the log looks a bit weird. level=error?

**Comment by jliebert** [comment]
Hello, 

If trustedCIDRS is empty the plugin fallback to pull CIDRs at startup/change traefik setup.
RefreshInterval can't be disabled, it's only minimal value of 5 minutes, but you can use a huge value.

Are you shure that '{{env "$CLOUDFLARE_IPv4,$CLOUDFLARE_IPv6"}}' is correctly evaluated, it shoud not be written '{{env "$CLOUDFLARE_IPv4}},{{env "$CLOUDFLARE_IPv6"}}' ?

For the log level, this is a issue from Traefik, a plugin can not interract with log level of Traefik: https://github.com/traefik/traefik/issues/8204

**Comment by alexander-zimmermann** [comment]
Hey,

1.  Your documentation says "When trustedCIDRs is empty, Cloudflare's CIDRs will be refreshed after this duration. Using a value of 0 seconds disables the refresh."  So I assume that a 0 will disable the refresh ;-)
2.  Yes {{env "$CLOUDFLARE_IPv4,$CLOUDFLARE_IPv6"}} works fine. Tested. {{env "$CLOUDFLARE_IPv4}},{{env "$CLOUDFLARE_IPv6"}} gives a parser error (tested w/ crowedsec plugin)
3. Bug understood, but for example the log output from crowedsec plugin looks better:
```
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/03/24 20:55:10 ServeHTTP ip:2a02:578:8513:1100:e02a:8140:4961:86eb isTrusted:false
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/03/24 20:55:10 cache:GetDecision ip:2a02:578:8513:1100:e02a:8140:4961:86eb
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/03/24 20:55:10 ServeHTTP:getDecision ip:2a02:578:8513:1100:e02a:8140:4961:86eb isBanned:false cache:miss
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/03/24 20:55:10 cache:SetDecision ip:2a02:578:8513:1100:e02a:8140:4961:86eb isBanned:false duration:60s
```

Thanks for the nice plugin
Alex

**Comment by jliebert** [comment]
Hi,

1. My apologies (I contradict my first answer), a value of 0 seconds disable the refresh as it's written in documentation. But if trustedCIDRS is empty the plugins fallback to a fresh CIDRS from Cloudflare API one time for each cloudflare midleware used. 
3. I think something goes wrong with {{env "$CLOUDFLARE_IPv4,$CLOUDFLARE_IPv6"}} so you get a refresh of CIDRS at startup of middleware. The value must be provided as yaml array, not a string separated by commas. This wrong formating should be better logged.
4. Logs CrowdsecBouncerTraefikPlugin bypass totaly standard logs outpout of Traefik, I prefer provide output to Traefik (with the format of traefik logs) instead of send it to other output with custom format. I hope in futur to be able to tune level from Traefik level.

Regards,

Julien

**Comment by alexander-zimmermann** [comment]
Hey Julien,

1. fine
2. Understood. So a '[{{env "$CLOUDFLARE_IPv4,$CLOUDFLARE_IPv6"}}]' should work. Let me test
3. fine

**Comment by alexander-zimmermann** [comment]
I follow the explanation at https://stackoverflow.com/questions/60273841/use-environment-variables-within-a-traefik-dynamic-configuration

With the result, I believe that works:

```
  1 http:
  2   middlewares:
  3     cloudflare:
  4       plugin:
  5         cloudflare:
  6           debug: true
  7           trustedCIDRs: [{{ expandenv "$CLOUDFLARE_IPv4,$CLOUDFLARE_IPv6" }}]
  8           allowedCIDRs: [{{ expandenv "$LOCAL_IPv4"}}]
  9           refreshInterval: 0
 10           overwriteRequestHeader: false
```

**Comment by alexander-zimmermann** [comment]
Thanks for the support
