### ISSUE TITLE
Compatibility with traefik 3

### ISSUE THREAD

**Issue by opipenbe** [agence-gaya/traefik-plugin-cloudflare#3]
Is this plugin compatible with traefik 3? For instance ipwhitelist middleware is deprecated since traefik 3 and it is suggested to use IPAllowList instead: https://doc.traefik.io/traefik/middlewares/http/ipallowlist/

**Comment by jliebert** [comment]
Hi, not tested yet with traefik 3, but it should.
This plugins is independant  of the standard middlewares provided by traefik, so it's not concerned by IPAllowList vs IPWhiteList.

Regards,

**Comment by opipenbe** [comment]
Hi and thank you for this information!

I am currently testing this plugin with traefik v3 using ipwhitelist or ipallowlist middleware, but I am unable to get it working.

In the traefik debug log I can see:
`Rejecting IP <cloudflare ip>: "<cloudflare ip>" matched none of the trusted IPs`

So I assume that for some reason RemoteAddress is not overwritten by CF-Connecting-IP.

**Comment by jliebert** [comment]
Hi, the "cloudflare ip" is it a real cloudflare ip?
Cloudflare plugin has required stuff to deny client not from cloudflare.
Why did you need ipallowlist?

**Comment by opipenbe** [comment]
Hello

Yes, in the logs it is a REAL cloudflare IP.

In my case I need IPAllowList for allowing ONLY some clients (list of IPs) from Cloudflare to specifc ingressroute.

**Comment by jliebert** [comment]
Hi, if you have the the message  "cloudflare ip" matched none of the trusted IPs, and the ip is from Cloudflare, your trusted ip list is wrong in your setup.

**Comment by opipenbe** [comment]
Thank you, you are right! 

I was able to get it working. Previously I was overthinking with options. Actually this plugin default options work in my use case as well.

**Comment by jliebert** [comment]
Perfect, and happy to know that work on Traefik 3.

Regards,
