### ISSUE TITLE
Doesn't seem to report the correct IP in traefik logs

### ISSUE THREAD

**Issue by fma965** [agence-gaya/traefik-plugin-cloudflare#4]
Doesn't seem to report the correct IP in traefik logs

![image](https://github.com/user-attachments/assets/428a36e1-16b2-4dc9-a636-12a16e020d7d)

![image](https://github.com/user-attachments/assets/cb878b06-c6b3-4fd1-a0be-fa406c7931a6)

![image](https://github.com/user-attachments/assets/a4787e79-94e0-415a-8c3f-b3879dc6bc3b)

**Comment by fma965** [comment]
--accesslog.fields.headers.defaultmode=keep allows me to get what i want but i do wonder if it should have also updated the standard ClientHost/Addr values?

**Comment by jliebert** [comment]
Yes the real client IP adresse at network level can not be replaced, it's only manipulation of header request.

**Comment by fma965** [comment]
Makes sense, thanks. adding the required headers and modified grafana queries works around it
